server:
  port: 8888

grpc:
  server:
    port: 5055
    health-service-enabled: false
    shutdown-grace-period: PT30S
  client:
    greeting:
      address: static://127.0.0.1:5055
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT